//
//  ProgramSheetData.swift
//  dogApp
//
//  Created by Kaspars Jelaiskis on 11/01/2024.
//

import Foundation

struct ProgramSheetStructure: Identifiable, Codable, Equatable {
    let id: Int
    let title: String
    let description: String
    let summary: String?
    let image: String

    
    enum CodingKeys: String, CodingKey {
        case id
        case title
        case description
        case summary
        case image
    }
    
    static func ==(lhs: ProgramSheetStructure, rhs: ProgramSheetStructure) -> Bool {
        return lhs.id == rhs.id
    }
    
    func presentSheet() -> ProgramSheetTemplate {
            return ProgramSheetTemplate(program: self)
        }
}

struct ProgramSheetArray: Codable {
    let programSheets: [ProgramSheetStructure]
    let total, skip, limit: Int
}


final class ProgramSheetDatabase {
    static let programs: [ProgramSheetStructure] = [
        ProgramSheetStructure(id: 1, title: "Sit", description: "• Hold a treat close to your dog's nose. Move your hand upwards, causing their head to follow the treat. \n \n  • As their head moves up, their bottom will naturally lower into a sitting position. \n \n • Once they are sitting, say \"Sit\" and give them the treat.\n \nMake \'Sit\' a spontaneous event. Ask for a sit during playtime, before heading outside, or even when you just want to revel in their cuteness. Turning it into a fun surprise keeps your pup on their toes (or paws).", summary: nil, image: "Sit"),
        ProgramSheetStructure(id: 2, title: "Recall", description: "• Find a quiet spot with minimal distractions. We're talking about a low-key environment where your pup can focus on you. \n \n• Pick a recall word that suits your style. \"Come,\" \"Here,\" or \"Zoom!\"—whatever tickles your fancy. Just be consistent and stick with it. Dogs are geniuses, but they like routine too! \n \n• Arm yourself with your pup's favorite treats. Every time they rush to you on command, shower them with praise and goodies. \n \n• Once your pup nails the basics, up the ante. Add a sprinkle of distractions—maybe a squeaky toy or a friend playing fetch nearby. \n \nRecall time is not drill sergeant time. Keep it upbeat and playful. Wiggle that treat bag, throw in some excited jumps, and make coming to you the highlight of their day.", summary: nil, image: "Come"),
        ProgramSheetStructure(id: 3, title: "Stay", description: "• Begin in a neutral, quiet space. Select a clear and simple cue for 'Stay.' It could be \"Stay,\" \"Hold,\" or \"Wait.\"  \n \n• Start with short intervals. Ask your pup to 'stay' for a few seconds, then gradually increase the duration as they get the hang of it.  \n \n• If your pup breaks the 'Stay' prematurely, no worries! Gently guide them back to the original spot and try again. Positive reinforcement and a calm demeanor work wonders.\n \n• Celebrate the victories, no matter how small. When your pup nails the 'Stay,' reward them with treats and genuine praise. Reinforce the idea that staying put comes with its perks.\n \nApply 'Stay' in practical scenarios. Use it before crossing the street, at the vet's office, or when guests arrive. The versatility of the command makes it a valuable tool in various situations.", summary: nil, image: "Stay"),
        ProgramSheetStructure(id: 4, title: "Eye contact", description: "This is a useful command to practice as it reinforces your dog to pay attention to you.\n\n• Choose a simple word or phrase like \"watch me\" or \"look at me\". This will serve as the command you use to instruct your dog to make eye contact with you. \n \n • Hold a treat up near your face to get their attention. \n \n • When you give the cue (e.g., \"watch me\"), wait for your dog to make eye contact with you. As soon as they do, immediately reward them with the treat and offer verbal praise. \n\nIncorporate the eye contact command into your daily interactions. Use it before meals, during walks, or when you're simply hanging out together. This builds a habit of checking in and connecting on a deeper level.", summary: nil, image: "Look"),
        ProgramSheetStructure(id: 5, title: "Leash and collar introduction", description: "• Begin by allowing your dog to sniff and investigate the collar. Pair the presence of the collar and leash with treats and praise to create a positive association. \n \n• Gently place the collar around your dog's neck for short periods while offering treats and affection. \n \n• Once your dog is comfortable with the collar, attach the leash and let it drag behind them while supervised. \n \n • Practice walking with your dog indoors, allowing them to get used to the sensation of the leash.", summary: nil, image: "collar"),
        ProgramSheetStructure(id: 6, title: "Start and stop", description: "• Start with practicing indoors. Begin walking, and encourage your dog to follow you. Use a positive verbal cue such as \"Let's go\". \n \n• Come to a complete stop and stand still. Use a verbal cue such as \"Wait\" to indicate that the dog should stop walking. Reinforce the stopped behavior with treats. If your dog sits and waits patiently during the stop, continue to reward them for maintaining calm behavior. \n \n• When you're ready to start walking again, use your verbal cue, encourage your dog to start walking with you, and reward them for following your lead. \n \n • Repeat the start and stop sequences during your training session. Gradually increase the duration of stops and the distance covered during walks.", summary: nil, image: "leashWalkingDetail"),
        ProgramSheetStructure(id: 7, title: "Direction change", description: "• Begin the training in a quiet environment with minimal distractions. A fenced yard or a quiet park can be suitable. \n \n• Start walking in a straight line with your dog beside or slightly behind you. Suddenly change direction by making a 90-degree turn to the left or right. Use a verbal cue to signal the change of the direction.  \n \n • As you turn, guide your dog with the leash to follow your lead. Use gentle pressure on the leash to guide them in the new direction. As your dog successfully changes direction with you, immediately reward them with treats and praise. \n \n• Practice direction changes in both left and right directions. As your dog becomes more proficient, gradually introduce distractions during your walks.", summary: nil, image: "directionChangeDetail"),
        ProgramSheetStructure(id: 8, title: "Loose leash walking", description: "• Start by using a comfortable collar or harness and a standard leash. Have a supply of small, tasty treats that your dog loves.\n \n• Decide on which side you want your dog to walk (commonly, it's the left side).\n \n• Begin walking, and as soon as your dog starts to pull, come to a gentle stop. Wait for your dog to come back to your side and loosen the leash.Reward with a treat and resume walking when the leash is loose. \n \n• Occasionally change direction during the walk without warning. Reward your dog frequently for walking with a loose leash. Gradually reduce the frequency of treats as your dog becomes more consistent.", summary: nil, image: "looseLeash"),
        ProgramSheetStructure(id: 9, title: "Heel", description: "• Begin walking your dog with a loose leash, allowing them some freedom. Use a clear and consistent verbal cue, such as \"Heel,\" when you want your dog to walk by your side.\n \n• Reward your dog with treats and praise when they are in the desired heel position, walking closely by your side. Use a clicker or a verbal marker to signal the precise moment they are in the correct position. \n \n • Gradually introduce changes in direction during the walk, and encourage your dog to follow your lead. Reward them for adjusting their position accordingly.", summary: nil, image: "heel"),
        ProgramSheetStructure(id: 10, title: "Office desensitization", description: "• Start by bringing your dog to the office during off-hours when the environment is quieter. This allows your dog to explore and get used to the new surroundings without the added stress of a busy office. \n \n• Introduce your dog to the specific areas they'll be spending time in, such as your workspace or designated dog-friendly zones. Let them sniff around and get comfortable in these spaces. \n \n • If possible, introduce your dog to a few colleagues during the off-hours visits. Ensure that these interactions are positive and pleasant.\n \n• As your dog becomes more comfortable, gradually increase the duration of their visits during regular office hours. This helps them acclimate to the increased activity and noise levels", summary: "Expose your dog to the sights, sounds, and smells of the office in a controlled and positive manner.", image: "officeIntro"),
        ProgramSheetStructure(id: 11, title: "Place", description: "• Choose a comfy spot for your dog to stay, like a dog bed or a designated area on the floor. \n \n • You'll need treats and a clicker (optional) for positive reinforcement. \n \n • Using a leash, stand by the chosen spot and say your command, like \"place\" or \"bed.\" \n \n • Use a treat to guide your dog onto the spot. Make sure they're fully on it before rewarding. \n \n • Click (if using a clicker) and treat immediately. Offer verbal praise like \"Good job!\" \n \n • Start waiting a few seconds before rewarding to build patience.", summary: "Teaching your dog to \"go to place\" is a handy command that can make your life easier. Follow these steps.", image: "Place"),
        ProgramSheetStructure(id: 12, title: "Greet politely", description: "• Ensure your dog has a solid understanding of basic commands such as sit, stay, and come. These commands will be the foundation for teaching polite greetings. \n \n • When your dog jumps up, avoid giving them attention. Turn away, fold your arms, and ignore them until they have all four paws on the ground. This teaches them that jumping results in a loss of attention. \n \n • Encourage your dog to sit when they approach people. Reward and praise them when they sit calmly. \n \n • Before guests or strangers approach, ask your dog to sit. If they sit, reward them. If they don't, use a leash or other control measures to prevent jumping and guide them into a sit position. \n \n • Train your dog to offer an alternative behavior when they're excited, such as holding a toy in their mouth. This can redirect their energy in a positive way. \n \n • Enlist the help of friends and family to practice polite greetings. Ask them to approach your dog calmly and reward the dog for sitting calmly rather than jumping.", summary: "Dogs naturally express excitement and affection by jumping, but it's crucial to redirect this behavior in a way that is more acceptable for human interactions.", image: "greetNicely"),
        ProgramSheetStructure(id: 13, title: "Safe space", description: "• Provide a comfortable bed or mat for your dog to lie on. Choose a bed that offers adequate support and is large enough for them to stretch out comfortably. \n \n • Bring in familiar items from home, such as your dog's favorite blanket or toy. Having familiar scents around can help your dog feel more at ease in the new environment. \n \n • Choose a quiet and relatively secluded area for your dog's space. This helps minimize distractions and allows your dog to relax without being constantly stimulated by the surrounding activity. \n \n • Always have a clean water bowl available for your dog. Hydration is crucial, especially if they spend extended periods in the office. \n \n • Provide a selection of toys and chewables to keep your dog entertained during quiet moments. Interactive toys that dispense treats can be particularly engaging. \n \n • Schedule regular breaks for your dog to stretch their legs, go for short walks, and have bathroom breaks. Regular breaks help prevent restlessness and promote overall well-being.", summary: "Creating a comfortable space for your dog in an office environment is important to help them feel secure and relaxed.", image: "inOffice"),
        ProgramSheetStructure(id: 14, title: "Socialization", description: "Introduce your dog gradually to different environments, people, and animals, starting with less challenging situations. \n \n • Provide opportunities for your dog to interact with other well-behaved dogs. This helps them develop appropriate social skills and learn how to communicate with others. \n \n • Well-socialized dogs are less likely to display aggressive behaviors towards other dogs. Positive interactions help reduce fear and anxiety, lowering the likelihood of defensive aggression. \n \n • Through interactions with other dogs, your dog learns to interpret and respond to social cues. This skill is valuable for preventing misunderstandings and conflicts in various social settings. \n \n • When introducing your dog to a new canine companion, do so in a supervised and controlled manner. Allow the dogs to sniff and greet each other gradually, observing their body language for signs of comfort or discomfort.", summary: "Begin socializing your dog as early as possible, ideally during their puppyhood to build a foundation for positive behavior.", image: "officeGreet"),
                
    ]
}
